SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
    from PRODUCT P
        join OFFLINE_SALE S
            ON P.PRODUCT_ID = S.PRODUCT_ID
        GROUP BY P.PRODUCT_CODE
        ORDER BY SALES DESC, P.PRODUCT_CODE ASC