SELECT BOOK_ID, AUTHOR_NAME, 
    TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') as PUBLISHED_DATE
        FROM BOOK B
        JOIN AUTHOR A
            ON B.AUTHOR_ID = A.AUTHOR_ID
                WHERE CATEGORY = '경제' order by PUBLISHED_DATE;