SELECT 
    BOOK.CATEGORY ,
    SUM(bs.SALES) TOTAL_SALES 
FROM BOOK
JOIN BOOK_SALES bs
    ON BOOK.BOOK_ID = bs.BOOK_ID
WHERE SALES_DATE like '2022-01-%'
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY;